-- MySQL Script generated by MySQL Workbench
-- Sat Apr 22 22:29:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SEP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SEP` ;

-- -----------------------------------------------------
-- Schema SEP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SEP` DEFAULT CHARACTER SET utf8 ;
USE `SEP` ;

-- -----------------------------------------------------
-- Table `SEP`.`escuelas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEP`.`escuelas` ;

CREATE TABLE IF NOT EXISTS `SEP`.`escuelas` (
  `id` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `nivel` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `nivel_idx` (`nivel` ASC) VISIBLE,
  CONSTRAINT `nivel`
    FOREIGN KEY (`nivel`)
    REFERENCES `SEP`.`nivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SEP`.`nivel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEP`.`nivel` ;

CREATE TABLE IF NOT EXISTS `SEP`.`nivel` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SEP`.`trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEP`.`trabajadores` ;

CREATE TABLE IF NOT EXISTS `SEP`.`trabajadores` (
  `rfc` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apPaterno` VARCHAR(45) NOT NULL,
  `apMaterno` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `escuela` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`rfc`),
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC) VISIBLE,
  INDEX `escuela_idx` (`escuela` ASC) VISIBLE,
  CONSTRAINT `escuela`
    FOREIGN KEY (`escuela`)
    REFERENCES `SEP`.`escuelas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `SEP` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

USE `SEP`;
DROP  IF EXISTS `SEP`.`routine1`;

DELIMITER $$
USE `SEP`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
